// <auto-generated />
using ImperialAuto.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImperialAuto.Infrastructure.Migrations
{
    [DbContext(typeof(ImperialAutoDbContext))]
    [Migration("20251124212444_ImperAutoFirst")]
    partial class ImperAutoFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImperialAuto.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "Images/toyota.png",
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("EngineTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("EngineTypeId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.CarColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Чорний"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Білий"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Сірий"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Жовтий"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Червоний"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Синій"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Темно-синій"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Зелений"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Фіолетовий"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Помаранчевий"
                        });
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.EngineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EngineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FuelType = "Бензин"
                        },
                        new
                        {
                            Id = 2,
                            FuelType = "Дизель"
                        },
                        new
                        {
                            Id = 3,
                            FuelType = "Бензин/Газ"
                        },
                        new
                        {
                            Id = 4,
                            FuelType = "Гібрид (Бензин/Електро)"
                        },
                        new
                        {
                            Id = 5,
                            FuelType = "Електро"
                        });
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.Car", b =>
                {
                    b.HasOne("ImperialAuto.Domain.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialAuto.Domain.Entities.CarColor", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialAuto.Domain.Entities.EngineType", "EngineType")
                        .WithMany("Cars")
                        .HasForeignKey("EngineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("EngineType");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.CarImage", b =>
                {
                    b.HasOne("ImperialAuto.Domain.Entities.Car", "Car")
                        .WithMany("ImageUrls")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.Car", b =>
                {
                    b.Navigation("ImageUrls");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.CarColor", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ImperialAuto.Domain.Entities.EngineType", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
